/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model
 */
export interface Model {
    /**
     * 
     * @type {number}
     * @memberof Model
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Model
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    thumbnailPath?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Model
     */
    imagePaths?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Model
     */
    modelPaths?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    creator?: string;
    /**
     * 
     * @type {string}
     * @memberof Model
     */
    creatorUrl?: string;
}

/**
 * Check if a given object implements the Model interface.
 */
export function instanceOfModel(value: object): value is Model {
    return true;
}

export function ModelFromJSON(json: any): Model {
    return ModelFromJSONTyped(json, false);
}

export function ModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'price': json['price'] == null ? undefined : json['price'],
        'description': json['description'] == null ? undefined : json['description'],
        'thumbnailPath': json['thumbnailPath'] == null ? undefined : json['thumbnailPath'],
        'imagePaths': json['imagePaths'] == null ? undefined : json['imagePaths'],
        'modelPaths': json['modelPaths'] == null ? undefined : json['modelPaths'],
        'creator': json['creator'] == null ? undefined : json['creator'],
        'creatorUrl': json['creatorUrl'] == null ? undefined : json['creatorUrl'],
    };
}

export function ModelToJSON(value?: Model | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'price': value['price'],
        'description': value['description'],
        'thumbnailPath': value['thumbnailPath'],
        'imagePaths': value['imagePaths'],
        'modelPaths': value['modelPaths'],
        'creator': value['creator'],
        'creatorUrl': value['creatorUrl'],
    };
}

